/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_supprimer (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_alert (void);
GtkWidget* create_gestionfiche1 (void);
GtkWidget* create_gestionfiche2 (void);
GtkWidget* create_gestionfiche3 (void);
GtkWidget* create_menu_uti (void);
GtkWidget* create_Gestion_Uti (void);
GtkWidget* create_Add_Uti (void);
GtkWidget* create_Edit_Uti (void);
GtkWidget* create_Delete_Uti (void);
GtkWidget* create_Show_Uti (void);
GtkWidget* create_Pourcentage (void);
